# Generated by Django 5.1.2 on 2024-10-21 12:27

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(max_length=50)),
                ('android', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('1', 'en'), ('2', 'vi'), ('3', 'jp'), ('4', 'fr')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic_api.part')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isListening', models.BooleanField(default=True)),
                ('score', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic_api.test')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
                ('option_a', models.TextField(blank=True)),
                ('option_b', models.TextField(blank=True)),
                ('option_c', models.TextField(blank=True)),
                ('option_d', models.TextField(blank=True)),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('isRelease', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic_api.part')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic_api.test')),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.TextField(blank=True)),
                ('option_b', models.TextField(blank=True)),
                ('option_c', models.TextField(blank=True)),
                ('option_d', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('language_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toeic_api.language')),
                ('question_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toeic_api.question')),
            ],
        ),
    ]
